set_target_properties( squawk
     PROPERTIES COMPILE_FLAGS "-DDEFAULT_RAM_SIZE=12*1024 -DSQUAWK_64=false -D_GNU_SOURCE -DNRF51 -DPLATFORM_TYPE_BARE_METAL=1 -DMACROIZE -DPLATFORM_BIG_ENDIAN=false -DPLATFORM_UNALIGNED_LOADS=false" )
