# target specific part
RAM_SIZE ?= 13*1024
SERVICE_CHUNK_SIZE ?= 1024
TARGET = NUCLEO_L476RG
MCU = STM32L4
VENDOR = STM
DEVICE = NUCLEO_L476RG
CFLAGS_ARCH = -mthumb -mcpu=cortex-m4
LIBDIR = $(MBED)/TARGET_$(TARGET)/TOOLCHAIN_GCC_ARM
LINKERSCRIPT = $(LIBDIR)/STM32L476XX.ld
