-include target.mk

AT ?= @
CFLAGS_OPTS = -Os -mlongcalls -mforce-l32 -mtext-section-literals -ffunction-sections -fdata-sections
CFLAGS_DEP = -MD
CFLAGS += -std=gnu99 -Dprintf=os_printf_plus

JAVA = java
JAVAC = javac
JAR = jar
FIND = find
CC = xtensa-lx106-elf-cc
AR = xtensa-lx106-elf-ar
OBJCOPY = xtensa-lx106-elf-objcopy
AWK = awk
EGREP = egrep
CAT = cat

SQUAWK_TOP = squawk
BUILD_TOP ?= build
LINKERSCRIPT = esp8266.ld
JARFILE = classes.jar
JARFILES = $(JARFILE) $(SQUAWK_TOP)/cldc/classes.target.jar
DCA_CONFIG = dca.config
WIFI_CONFIG = $(SQUAWK_TOP)/targets/esp8266/wifi.config
CONNECTOR_CONFIG = $(SQUAWK_TOP)/targets/esp8266/connector.config
FASTALLOC = true
#ROMIZER_FLAGS += -stripSystemClassName

BUILD_FLAGS += -DMACROIZE -D_GNU_SOURCE -DSQUAWK_64=false -DPLATFORM_BIG_ENDIAN=false -DPLATFORM_UNALIGNED_LOADS=false -DPLATFORM_TYPE_BARE_METAL=1
BUILD_FLAGS += -DDEFAULT_RAM_SIZE=$(RAM_SIZE)
BUILD_FLAGS += -DSERVICE_CHUNK_SIZE=$(SERVICE_CHUNK_SIZE)
BUILD_FLAGS += -DFASTALLOC=$(FASTALLOC)
BUILD_FLAGS += -DGCC_OPTIMIZE_INTERPRETER_LOOP=1
BUILD_FLAGS += -DMINIMAL_ERROR_REPORT
BUILD_FLAGS += -DHAS_METHOD_OFFSETS=1

INCLUDE_DIRS += $(ESP_SDK)/include .
INCLUDE_DIRS += $(BUILD_TOP)/vmcore/src/vm $(SQUAWK_TOP)/vmcore/src/vm $(SQUAWK_TOP)/vmcore/src/vm $(SQUAWK_TOP)/vmcore/src/vm/fp $(SQUAWK_TOP)/vmcore/src/rts/esp8266
INCLUDE_DIRS += $(ESP_SDK)/include $(ESP_SDK)/driver_lib/include/driver $(ESP_SDK)/../esp-open-lwip/include
INCLUDE_DIRS += $(SQUAWK_TOP)/targets/esp8266/src/native
INCLUDE_DIRS += $(SQUAWK_TOP)/spiffs/latest/src
#INCLUDE_DIRS += $(SQUAWK_TOP)/mbedtls/latest/include
CFLAGS += $(CFLAGS_ARCH) $(DEVICE_OPTIONS) $(BUILD_FLAGS) $(patsubst %,-I%,$(INCLUDE_DIRS)) $(CFLAGS_OPTS) $(CFLAGS_DEP)
LDFLAGS += $(LDLAGS_ARCH) -T$(LINKERSCRIPT) -uuser_init -Wl,--gc-sections -Wl,--Map=$(@:.elf=.map) -Wl,--cref
#LDSUFFIXES += -L$(SQUAWK_TOP)/mbedtls
LDSUFFIXES += -L$(BUILD_TOP)
LIBAR = $(BUILD_TOP)/libsquawk.a
LIBS = crypto main net80211 wpa wpa2 wps lwip pp phy driver gcc cirom m squawk
LDSUFFIXES += -L$(ESP_SDK)/lib -L$(ESP_SDK)/ld -nostdlib -Wl,--start-group $(patsubst %,-l%,$(LIBS)) -Wl,--end-group 
TMP = /tmp/squawk.$(shell pwd | sum | awk '{print $$1}')
CLEAN_TARGETS = $(BUILD_TOP) $(JARFILE) $(TMP) classes

C_SOURCE_DIRS = src/native $(SQUAWK_TOP)/vmcore/src/vm/fp $(SQUAWK_TOP)/vmcore/src/vm $(SQUAWK_TOP)/vmcore/src/rts/esp8266 $(SQUAWK_TOP)/targets/esp8266/src/native
C_SOURCE_DIRS += $(SQUAWK_TOP)/spiffs/latest/src
C_SOURCE_FILES  = $(shell for i in $(patsubst %,%/*.c,$(C_SOURCE_DIRS)); do if [ -f $$i ]; then basename $$i; fi; done)
OBJECT_DIR = $(BUILD_TOP)/obj
OBJECT_FILES = $(patsubst %.c,$(OBJECT_DIR)/%.o,$(C_SOURCE_FILES))
OBJECT_FILES += $(OBJECT_DIR)/squawk.suite.o
DEPENDS = $(patsubst %.o,%.d,$(OBJECT_FILES))

JAVA_SOURCE_DIRS = src/classes $(SQUAWK_TOP)/gcf/src $(SQUAWK_TOP)/targets/esp8266/src/classes 
JAVA_SOURCE_FILES = $(shell $(FIND) $(JAVA_SOURCE_DIRS) -name '*.java' -print)

vpath %.c $(C_SOURCE_DIRS)

all: dirs $(JARFILE) romize compile link bin hex

dirs:
	$(AT)mkdir -p $(OBJECT_DIR)

$(JARFILE): $(JAVA_SOURCE_FILES)
	$(AT)rm -rf classes
	$(AT)mkdir -p classes
	$(AT)$(JAVAC) -bootclasspath $(SQUAWK_TOP)/cldc/classes.target.jar -d classes $(JAVA_SOURCE_FILES)
	$(AT)$(JAR) cf $(JARFILE) -C classes .
	$(AT)$(JAVA) -cp $(SQUAWK_TOP)/build.jar:$(SQUAWK_TOP)/tools/asm-all-5.2.jar com.sun.squawk.builder.asm.MainFinder $(JARFILE) > $(BUILD_TOP)/MAIN_CLASS_NAME

romize: $(BUILD_TOP)/squawk.suite.c

$(BUILD_TOP)/squawk.suite.c: $(JARFILES)
	$(AT)rm -rf $(TMP)
	$(AT)mkdir -p $(TMP)/classes $(BUILD_TOP)
	$(AT)for i in $(JARFILES); do (cd $(TMP)/classes; $(JAR) x) < $$i; done
	$(AT)$(JAVA) -Xbootclasspath/a:$(SQUAWK_TOP)/tools/asm-all-5.2.jar -cp $(SQUAWK_TOP)/build.jar com.sun.squawk.builder.glue.NativeGlueGen -d:$(BUILD_TOP) $(TMP)/classes
	$(AT)tar cf - -C $(BUILD_TOP)/cldc/classes .  | (cd $(TMP)/classes; tar xf -)
	$(AT)mkdir -p $(TMP)/classes2
	$(AT)jar cf $(TMP)/classes.jar -C $(TMP)/classes .
	$(AT)cp $(SQUAWK_TOP)/builder/$(DCA_CONFIG) $(TMP)
	$(AT)cp $(SQUAWK_TOP)/builder/$(GC_DCA_CONF) $(TMP)		
	$(AT)echo "$$(cat $(BUILD_TOP)/MAIN_CLASS_NAME).main([Ljava/lang/String;)V" >> $(TMP)/$(DCA_CONFIG)
	$(AT)$(JAVA) -cp $(SQUAWK_TOP)/build.jar:$(SQUAWK_TOP)/tools/asm-all-5.2.jar com.sun.squawk.builder.dca.DeadCodeAnalyzer -w -config $(WIFI_CONFIG),$(CONNECTOR_CONFIG),$(TMP)/$(DCA_CONFIG),$(TMP)/$(GC_DCA_CONF) -o $(TMP)/unused -u $(TMP)/used -i $(TMP)/itf -x $(TMP)/xref $(TMP)/classes.jar
	$(AT)cat $(TMP)/itf >> $(TMP)/unused
	$(AT)$(JAVA) -cp $(SQUAWK_TOP)/build.jar:$(SQUAWK_TOP)/tools/asm-all-5.2.jar com.sun.squawk.builder.filter.Filter $(TMP)/unused $(TMP)/classes.jar $(TMP)/classes2.jar
	$(AT)$(JAVA) -cp $(SQUAWK_TOP)/build.jar:$(SQUAWK_TOP)/tools/asm-all-5.2.jar com.sun.squawk.builder.dca.DeadCodeAnalyzer -w -config $(WIFI_CONFIG),$(CONNECTOR_CONFIG),$(TMP)/$(DCA_CONFIG),$(TMP)/$(GC_DCA_CONF) -o $(TMP)/unused2 -u $(TMP)/used2 -i $(TMP)/itf2 -x $(TMP)/xref2 $(TMP)/classes2.jar
	$(AT)cat $(TMP)/itf2 >> $(TMP)/unused2
	$(AT)$(JAVA) -cp $(SQUAWK_TOP)/build.jar:$(SQUAWK_TOP)/tools/asm-all-5.2.jar com.sun.squawk.builder.filter.Filter $(TMP)/unused2 $(TMP)/classes2.jar $(TMP)/classes3.jar
	$(AT)(cd $(TMP)/classes2; jar xf $(TMP)/classes3.jar)
	$(AT)mkdir -p $(TMP)/weaved
	$(AT)$(JAVA) -cp $(SQUAWK_TOP)/tools/retroweaver-all-squawk.jar:$(SQUAWK_TOP)/hosted-support/classes.jar:$(SQUAWK_TOP)/romizer/classes.jar:$(SQUAWK_TOP)/cldc/classes.jar:$(SQUAWK_TOP)/translator/classes.jar com.sun.squawk.SquawkRetroWeaver $(TMP)/classes2 $(TMP)/weaved
	$(AT)mkdir -p $(TMP)/j2meclasses
	$(AT)$(SQUAWK_TOP)/tools/linux-x86/preverify -classpath $(SQUAWK_TOP)/cldc/classes.target.jar -d $(TMP)/j2meclasses $(TMP)/weaved
	$(AT)$(JAVA) -cp $(BUILD_TOP)/cldc/classes:$(SQUAWK_TOP)/hosted-support/classes.jar:$(SQUAWK_TOP)/romizer/classes.jar:$(SQUAWK_TOP)/cldc/classes.jar:$(SQUAWK_TOP)/translator/classes.jar \
		com.sun.squawk.Romizer $(ROMIZER_FLAGS) -strip:a -mainclass:$(shell cat $(BUILD_TOP)/MAIN_CLASS_NAME) -DGC_com.sun.squawk.Lisp2Collector=false -DPLATFORM_TYPE_DELEGATING=false \
		-DGC_com.sun.squawk.Lisp2GenerationalCollector=false -DPLATFORM_TYPE_SOCKET=false \
		-DMACROIZE=true -DGC_com.sun.squawk.CheneyCollector=true -DPLATFORM_TYPE_BARE_METAL=true -DPLATFORM_TYPE_NATIVE=false \
		-d:$(BUILD_TOP) -o:squawk -arch:X86 -endian:little -cp:$(TMP)/j2meclasses -java5cp:$(TMP)/j2meclasses -nometadata -noApi $(TMP)/j2meclasses
	$(AT)$(JAVA) -cp $(SQUAWK_TOP)/hosted-support/classes.jar:$(SQUAWK_TOP)/mapper/classes.jar:$(SQUAWK_TOP)/cldc/classes.jar:$(SQUAWK_TOP)/translator/classes.jar \
		com.sun.squawk.suiteconverter.FlashConverter -c $(BUILD_TOP)/squawk.suite 0
	$(AT)$(EGREP) '#define com_sun_squawk_VM ' $(BUILD_TOP)/vmcore/src/vm/classes.h | $(AWK) '{print $$3}' > $(BUILD_TOP)/cid
	$(AT)$(JAVA) -cp $(SQUAWK_TOP)/hosted-support/classes.jar:$(SQUAWK_TOP)/mapper/classes.jar:$(SQUAWK_TOP)/cldc/classes.jar:$(SQUAWK_TOP)/translator/classes.jar \
		com.sun.squawk.suiteconverter.FlashConverter -m:$$($(CAT) $(BUILD_TOP)/cid) $(BUILD_TOP)/squawk.suite 0 > $(BUILD_TOP)/vmcore/src/vm/methodOffsets.h

buildflags:
	$(AT)echo "#define BUILD_FLAGS \""$(BUILD_FLAGS)"\"" > $(TMP)/buildflags.h
	$(AT)if [ -f $(BUILD_TOP)/vmcore/src/vm/native.c.inc ]; then \
		echo "#define INCLUDE_NATIVE" >> $(TMP)/buildflags.h; \
	fi
	$(AT)echo "#define MAIN_CLASS_NAME "$(shell cat $(BUILD_TOP)/MAIN_CLASS_NAME) >> $(TMP)/buildflags.h
	$(AT)if [ -f $(BUILD_TOP)/vmcore/src/vm/buildflags.h ]; then \
	    diff $(TMP)/buildflags.h $(BUILD_TOP)/vmcore/src/vm/buildflags.h > /dev/null || cp $(TMP)/buildflags.h $(BUILD_TOP)/vmcore/src/vm/buildflags.h; \
	else \
		cp $(TMP)/buildflags.h $(BUILD_TOP)/vmcore/src/vm/buildflags.h; \
	fi

compile: buildflags $(OBJECT_FILES) archive

archive:
	$(AT)$(AR) r $(LIBAR) $(OBJECT_FILES)

-include $(DEPENDS)

$(OBJECT_DIR)/squawk.suite.o: $(BUILD_TOP)/squawk.suite.c
	$(AT)$(CC) -c $(CFLAGS) -o $(OBJECT_DIR)/squawk.suite.o $<

$(OBJECT_DIR)/%.o: %.c
	$(AT)$(CC) -c $(CFLAGS) -o $@ $<

%.bin: %.elf
	esptool.py elf2image $^

$(BUILD_TOP)/squawk.elf : $(LIBAR)
	$(AT)$(CC) $(LDFLAGS) -o $@ build/obj/os.o build/obj/mem.o build/obj/ets_alt_task.o $(LDSUFFIXES)

link: $(BUILD_TOP)/squawk.elf
bin: $(BUILD_TOP)/squawk.bin

map:
	$(AT)java -cp $(SQUAWK_TOP)/hosted-support/classes.jar:$(SQUAWK_TOP)/mapper/classes.jar:$(SQUAWK_TOP)/cldc/classes.jar:$(SQUAWK_TOP)/translator/classes.jar com.sun.squawk.ObjectMemoryMapper -o:$(BUILD_TOP)/squawk.suite.map -cp:$(TMP)/j2meclasses $(BUILD_TOP)/squawk.suite

clean:
	$(AT)rm -rf $(CLEAN_TARGETS)

.PHONY: all dirs romize buildflags compile link bin hex map clean
