# target specific part
RAM_SIZE ?= 12*1024
TARGET = NRF51_MICROBIT
MCU = MCU_NRF51822
VENDOR = NORDIC
DEVICE = NRF51_MICROBIT
CFLAGS_ARCH = -mthumb -mcpu=cortex-m0
LIBDIR = $(MBED)/TARGET_$(TARGET)/TOOLCHAIN_GCC_ARM
LINKERSCRIPT = NRF51822.ld
CFLAGS += -DNRF51
