# target specific part
RAM_SIZE ?= 13*1024
SERVICE_CHUNK_SIZE ?= 1024
TARGET = LPC1768
MCU = LPC176X
VENDOR = NXP
DEVICE = MBED_LPC1768
CFLAGS_ARCH = -mthumb -mcpu=cortex-m3
LIBDIR = $(MBED)/TARGET_$(TARGET)/TOOLCHAIN_GCC_ARM
LINKERSCRIPT = $(LIBDIR)/LPC1768.ld
